# Generated by Django 4.2.6 on 2023-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ("username",)},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("dish_type",)},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
