# Generated by Django 4.2.6 on 2023-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
